name 'demoapp'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures demoapp'
long_description 'Installs/Configures demoapp'
version '0.1.0'
